# Generated by Django 5.1.7 on 2025-05-29 12:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=255)),
                ('_language', models.CharField(choices=[('sql', 'SQL'), ('ra', 'Relational Algebra')], db_column='language', default='sql', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
