# Generated by Django 5.1.7 on 2025-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
