# Generated by Django 5.1.7 on 2025-04-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('queries', '0002_alter_query_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(default='Query', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='projects.project'),
            preserve_default=False,
        ),
    ]
