# Generated by Django 5.1.7 on 2025-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_query_name_query_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-modified']},
        ),
    ]
