# Generated by Django 5.1.7 on 2025-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_alter_query_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='text',
            new_name='sql_text',
        ),
        migrations.AddField(
            model_name='query',
            name='language',
            field=models.CharField(choices=[('sql', 'SQL'), ('ra', 'Relational Algebra')], default='sql', max_length=16),
        ),
    ]
