# Generated by Django 5.1.7 on 2025-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_rename_text_query_sql_text_query_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='ra_text',
            field=models.TextField(blank=True),
        ),
    ]
