# Generated by Django 5.1.7 on 2025-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_query_ra_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ra_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='sql_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
