# Generated by Django 5.1.7 on 2025-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0007_alter_query_ra_text_alter_query_sql_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='ra_text',
        ),
        migrations.RemoveField(
            model_name='query',
            name='sql_text',
        ),
        migrations.AddField(
            model_name='query',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
