# Generated by Django 5.1.7 on 2025-05-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0008_remove_query_ra_text_remove_query_sql_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
