// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  ProjectsListData,
  ProjectsListResponse,
  ProjectsCreateData,
  ProjectsCreateResponse,
  ProjectsQueriesListData,
  ProjectsQueriesListResponse,
  ProjectsQueriesCreateData,
  ProjectsQueriesCreateResponse,
  QueriesUpdateData,
  QueriesUpdateResponse,
  QueriesPartialUpdateData,
  QueriesPartialUpdateResponse,
  QueriesDestroyData,
  QueriesDestroyResponse,
  QueriesExecutionsCreateData,
  QueriesExecutionsCreateResponse,
  UsersListData,
  UsersListResponse,
  UsersCreateData,
  UsersCreateResponse,
  UsersRetrieveData,
  UsersRetrieveResponse,
  UsersUpdateData,
  UsersUpdateResponse,
  UsersPartialUpdateData,
  UsersPartialUpdateResponse,
  UsersDestroyData,
  UsersDestroyResponse,
} from "./types.gen";

export class ProjectsService {
  /**
   * @param data The data for the request.
   * @param data.limit Number of results to return per page.
   * @param data.offset The initial index from which to return the results.
   * @returns PaginatedProjectList
   * @throws ApiError
   */
  public static projectsList(
    data: ProjectsListData = {},
  ): CancelablePromise<ProjectsListResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/projects/",
      query: {
        limit: data.limit,
        offset: data.offset,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Project
   * @throws ApiError
   */
  public static projectsCreate(
    data: ProjectsCreateData,
  ): CancelablePromise<ProjectsCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/projects/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.projectPk ID of the parent project
   * @returns Query
   * @throws ApiError
   */
  public static projectsQueriesList(
    data: ProjectsQueriesListData,
  ): CancelablePromise<ProjectsQueriesListResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/projects/{project_pk}/queries/",
      path: {
        project_pk: data.projectPk,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.projectPk ID of the parent project
   * @param data.requestBody
   * @returns Query
   * @throws ApiError
   */
  public static projectsQueriesCreate(
    data: ProjectsQueriesCreateData,
  ): CancelablePromise<ProjectsQueriesCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/projects/{project_pk}/queries/",
      path: {
        project_pk: data.projectPk,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }
}

export class QueriesService {
  /**
   * @param data The data for the request.
   * @param data.id ID of the query
   * @param data.requestBody
   * @returns Query
   * @throws ApiError
   */
  public static queriesUpdate(
    data: QueriesUpdateData,
  ): CancelablePromise<QueriesUpdateResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/queries/{id}/",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id ID of the query
   * @param data.requestBody
   * @returns QueryPartialUpdate
   * @throws ApiError
   */
  public static queriesPartialUpdate(
    data: QueriesPartialUpdateData,
  ): CancelablePromise<QueriesPartialUpdateResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/queries/{id}/",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id ID of the query
   * @returns void No response body
   * @throws ApiError
   */
  public static queriesDestroy(
    data: QueriesDestroyData,
  ): CancelablePromise<QueriesDestroyResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/queries/{id}/",
      path: {
        id: data.id,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id ID of the query
   * @returns QueryExecution
   * @throws ApiError
   */
  public static queriesExecutionsCreate(
    data: QueriesExecutionsCreateData,
  ): CancelablePromise<QueriesExecutionsCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/queries/{id}/executions/",
      path: {
        id: data.id,
      },
    });
  }
}

export class UsersService {
  /**
   * @param data The data for the request.
   * @param data.limit Number of results to return per page.
   * @param data.offset The initial index from which to return the results.
   * @returns PaginatedUserList
   * @throws ApiError
   */
  public static usersList(
    data: UsersListData = {},
  ): CancelablePromise<UsersListResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/users/",
      query: {
        limit: data.limit,
        offset: data.offset,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersCreate(
    data: UsersCreateData,
  ): CancelablePromise<UsersCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/users/",
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @returns User
   * @throws ApiError
   */
  public static usersRetrieve(
    data: UsersRetrieveData,
  ): CancelablePromise<UsersRetrieveResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/users/{id}/",
      path: {
        id: data.id,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersUpdate(
    data: UsersUpdateData,
  ): CancelablePromise<UsersUpdateResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/users/{id}/",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersPartialUpdate(
    data: UsersPartialUpdateData,
  ): CancelablePromise<UsersPartialUpdateResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/users/{id}/",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @returns void No response body
   * @throws ApiError
   */
  public static usersDestroy(
    data: UsersDestroyData,
  ): CancelablePromise<UsersDestroyResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/users/{id}/",
      path: {
        id: data.id,
      },
    });
  }
}
