// This file is auto-generated by @hey-api/openapi-ts

export type PaginatedQueryList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Query>;
};

export type PaginatedUserList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
};

export type PatchedQuery = {
  readonly id?: number;
  text?: string;
  readonly created?: string;
  readonly modified?: string;
};

export type PatchedUser = {
  readonly id?: number;
  email?: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created?: string;
  readonly modified?: string;
  last_login?: string | null;
};

export type Query = {
  readonly id: number;
  text: string;
  readonly created: string;
  readonly modified: string;
};

export type QueryExecution = {
  /**
   * Query result data if the query execution was successful
   */
  results?: QueryResultData;
  /**
   * Indicates if the query execution was successful
   */
  success: boolean;
};

export type QueryPartialUpdate = {
  /**
   * The updated query object after partial update.
   */
  query: Query;
  /**
   * Error message, if any occurred during update.
   */
  error?: string;
};

export type QueryResultData = {
  /**
   * List of column names from the query
   */
  columns: Array<string>;
  /**
   * List of query result rows
   */
  rows: Array<Array<string | null>>;
};

export type User = {
  readonly id: number;
  email: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created: string;
  readonly modified: string;
  last_login?: string | null;
};

export type QueriesListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type QueriesListResponse = PaginatedQueryList;

export type QueriesCreateData = {
  requestBody: Query;
};

export type QueriesCreateResponse = Query;

export type QueriesRetrieveData = {
  /**
   * A unique integer value identifying this query.
   */
  id: number;
};

export type QueriesRetrieveResponse = Query;

export type QueriesUpdateData = {
  /**
   * A unique integer value identifying this query.
   */
  id: number;
  requestBody: Query;
};

export type QueriesUpdateResponse = Query;

export type QueriesPartialUpdateData = {
  /**
   * A unique integer value identifying this query.
   */
  id: number;
  requestBody?: PatchedQuery;
};

export type QueriesPartialUpdateResponse = QueryPartialUpdate;

export type QueriesDestroyData = {
  /**
   * A unique integer value identifying this query.
   */
  id: number;
};

export type QueriesDestroyResponse = void;

export type QueriesExecutionsCreateData = {
  /**
   * A unique integer value identifying this query.
   */
  id: number;
};

export type QueriesExecutionsCreateResponse = QueryExecution;

export type UsersListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type UsersListResponse = PaginatedUserList;

export type UsersCreateData = {
  requestBody: User;
};

export type UsersCreateResponse = User;

export type UsersRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type UsersRetrieveResponse = User;

export type UsersUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
};

export type UsersUpdateResponse = User;

export type UsersPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
};

export type UsersPartialUpdateResponse = User;

export type UsersDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type UsersDestroyResponse = void;

export type $OpenApiTs = {
  "/api/queries/": {
    get: {
      req: QueriesListData;
      res: {
        200: PaginatedQueryList;
      };
    };
    post: {
      req: QueriesCreateData;
      res: {
        201: Query;
      };
    };
  };
  "/api/queries/{id}/": {
    get: {
      req: QueriesRetrieveData;
      res: {
        200: Query;
      };
    };
    put: {
      req: QueriesUpdateData;
      res: {
        200: Query;
      };
    };
    patch: {
      req: QueriesPartialUpdateData;
      res: {
        200: QueryPartialUpdate;
      };
    };
    delete: {
      req: QueriesDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/queries/{id}/executions/": {
    post: {
      req: QueriesExecutionsCreateData;
      res: {
        200: QueryExecution;
      };
    };
  };
  "/api/users/": {
    get: {
      req: UsersListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: UsersCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/users/{id}/": {
    get: {
      req: UsersRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: UsersUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: UsersPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: UsersDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
};
