# Generated by Django 5.1.7 on 2025-04-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='username',
            new_name='user',
        ),
    ]
