# Generated by Django 5.1.7 on 2025-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_rename_username_database_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL')], default='postgresql'),
        ),
    ]
