# Generated by Django 5.1.7 on 2025-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_database_created_database_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='type',
            new_name='database_type',
        ),
    ]
