# Generated by Django 5.1.7 on 2025-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('sql', 'SQL'), ('ra', 'Relational Algebra')], max_length=16),
        ),
    ]
